"""tables created

Revision ID: 1393308445ca
Revises: 
Create Date: 2025-09-23 13:00:56.320844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1393308445ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_created_by_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('products_updated_by_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_created_by_fkey'), 'products', type_='foreignkey')
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(op.f('products_created_by_fkey'), 'products', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('products_updated_by_fkey'), 'products', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('orders_created_by_fkey'), 'orders', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
