"""columns added

Revision ID: 898fb4c0d6a9
Revises: c87846d855fe
Create Date: 2025-09-25 15:49:30.780980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898fb4c0d6a9'
down_revision: Union[str, Sequence[str], None] = 'c87846d855fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###
