"""column added

Revision ID: cdcbc5bc00c6
Revises: c3ba362c8cf5
Create Date: 2025-09-25 17:50:32.924151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdcbc5bc00c6'
down_revision: Union[str, Sequence[str], None] = 'c3ba362c8cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('delivery_in_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'delivery_in_days')
    # ### end Alembic commands ###
